sudo: false
language: python
python:
  - "2.7"
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - mamba --enable-coverage  --format documentation
after_success:
  - coveralls
  - coverage report
